"""
JARVIS Word Document Generation Engine
Creates rich, formatted .docx files with:
- Title pages, headers, footers
- Multiple sections with headings
- Tables
- Embedded images
- Bullet/numbered lists
- Code blocks (styled monospace)
"""
import os
import io
import uuid
import datetime

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "output", "documents")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def _set_cell_bg(cell, hex_color: str):
    """Set table cell background color."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), hex_color)
    tcPr.append(shd)


def _add_header_footer(doc: Document, title: str, author: str):
    """Add styled header and footer to all sections."""
    section = doc.sections[0]

    # Header
    header = section.header
    header.is_linked_to_previous = False
    hdr_para = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
    hdr_para.clear()
    hdr_run = hdr_para.add_run(f"  {title}")
    hdr_run.font.size = Pt(9)
    hdr_run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)
    hdr_para.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # Footer
    footer = section.footer
    footer.is_linked_to_previous = False
    ftr_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    ftr_para.clear()
    date_str = datetime.datetime.now().strftime("%B %d, %Y")
    ftr_run = ftr_para.add_run(f"  Generated by JARVIS AI  •  {author}  •  {date_str}")
    ftr_run.font.size = Pt(8)
    ftr_run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    ftr_para.alignment = WD_ALIGN_PARAGRAPH.CENTER


def _add_title_page(doc: Document, title: str, subtitle: str, author: str):
    """Add a styled title page."""
    # Large title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_para.paragraph_format.space_before = Pt(80)
    title_para.paragraph_format.space_after = Pt(20)
    title_run = title_para.add_run(title)
    title_run.font.size = Pt(32)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

    # Subtitle
    if subtitle:
        sub_para = doc.add_paragraph()
        sub_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub_para.paragraph_format.space_after = Pt(40)
        sub_run = sub_para.add_run(subtitle)
        sub_run.font.size = Pt(16)
        sub_run.font.color.rgb = RGBColor(0x45, 0x55, 0x8C)

    # Author and date
    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta_para.add_run(f"{author}  •  {datetime.datetime.now().strftime('%B %Y')}")
    meta_run.font.size = Pt(11)
    meta_run.font.color.rgb = RGBColor(0x70, 0x70, 0x70)
    meta_run.font.italic = True

    # Horizontal rule
    doc.add_paragraph()
    rule_para = doc.add_paragraph()
    rule_run = rule_para.add_run("─" * 60)
    rule_run.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
    rule_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_page_break()


def _add_section_heading(doc: Document, text: str, level: int = 1):
    """Add a numbered heading with accent color."""
    style = f'Heading {min(level, 3)}'
    para = doc.add_heading(text, level=min(level, 3))
    for run in para.runs:
        if level == 1:
            run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)
            run.font.size = Pt(20)
        elif level == 2:
            run.font.color.rgb = RGBColor(0x45, 0x55, 0x8C)
            run.font.size = Pt(15)
        else:
            run.font.color.rgb = RGBColor(0x55, 0x66, 0x99)
            run.font.size = Pt(13)


def _add_paragraph(doc: Document, text: str, style: str = 'Normal'):
    """Add a body paragraph."""
    para = doc.add_paragraph(style=style)
    run = para.add_run(text)
    run.font.size = Pt(11)
    para.paragraph_format.space_after = Pt(6)
    return para


def _add_bullet_list(doc: Document, items: list, numbered: bool = False):
    """Add a bullet or numbered list."""
    style_name = 'List Number' if numbered else 'List Bullet'
    for item in items:
        para = doc.add_paragraph(style=style_name)
        run = para.add_run(str(item))
        run.font.size = Pt(11)


def _add_table(doc: Document, headers: list, rows: list):
    """Add a styled table with header row."""
    col_count = len(headers)
    table = doc.add_table(rows=1 + len(rows), cols=col_count)
    table.style = 'Table Grid'

    # Header row
    hdr_row = table.rows[0]
    for i, h in enumerate(headers):
        cell = hdr_row.cells[i]
        cell.text = str(h)
        _set_cell_bg(cell, '1A1A2E')
        for para in cell.paragraphs:
            for run in para.runs:
                run.font.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.size = Pt(10)

    # Data rows
    for r_idx, row_data in enumerate(rows):
        row = table.rows[r_idx + 1]
        bg = 'F0F2FF' if r_idx % 2 == 0 else 'FFFFFF'
        for c_idx, cell_val in enumerate(row_data):
            cell = row.cells[c_idx]
            cell.text = str(cell_val)
            _set_cell_bg(cell, bg)
            for para in cell.paragraphs:
                for run in para.runs:
                    run.font.size = Pt(10)

    doc.add_paragraph()


def _add_code_block(doc: Document, code: str, language: str = ""):
    """Add a styled monospace code block."""
    label_para = doc.add_paragraph()
    label_run = label_para.add_run(f"[{language.upper() or 'CODE'}]")
    label_run.font.size = Pt(8)
    label_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    code_para = doc.add_paragraph()
    code_para.paragraph_format.left_indent = Inches(0.3)
    code_para.paragraph_format.space_before = Pt(2)
    code_para.paragraph_format.space_after = Pt(8)

    code_run = code_para.add_run(code)
    code_run.font.name = 'Courier New'
    code_run.font.size = Pt(9)
    code_run.font.color.rgb = RGBColor(0x1A, 0x6E, 0x5A)

    # Light grey background via XML shading
    pPr = code_para._p.get_or_add_pPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), 'F4F4F4')
    pPr.append(shd)


def _embed_image(doc: Document, image_path: str, caption: str = "", width_inches: float = 5.5):
    """Embed an image file into the document with optional caption."""
    if not os.path.exists(image_path):
        _add_paragraph(doc, f"[Image not found: {image_path}]")
        return

    try:
        img_para = doc.add_paragraph()
        img_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = img_para.add_run()
        run.add_picture(image_path, width=Inches(width_inches))

        if caption:
            cap_para = doc.add_paragraph()
            cap_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            cap_run = cap_para.add_run(f"Figure: {caption}")
            cap_run.font.size = Pt(9)
            cap_run.font.italic = True
            cap_run.font.color.rgb = RGBColor(0x70, 0x70, 0x70)

        doc.add_paragraph()
    except Exception as e:
        _add_paragraph(doc, f"[Error embedding image: {str(e)}]")


def create_word_document(
    title: str,
    sections: list,
    subtitle: str = "",
    author: str = "JARVIS AI",
    filename: str = None,
    include_toc_marker: bool = True
) -> dict:
    """
    Create a rich Word document.

    `sections` is a list of dicts, each with:
    {
      "heading": "Section Title",         # Required
      "level": 1,                          # Optional, default 1
      "content": "Paragraph text...",      # Optional
      "bullets": ["item1", "item2"],       # Optional
      "numbered_list": ["step1", ...],     # Optional
      "table": {"headers": [...], "rows": [[...], ...]},  # Optional
      "code": "print('hello')",            # Optional
      "code_lang": "python",               # Optional
      "image_path": "/path/to/img.png",   # Optional
      "image_caption": "Description",     # Optional
    }
    """
    if not filename:
        safe_title = title[:40].strip().replace(' ', '_').replace('/', '_')
        filename = f"{safe_title}_{uuid.uuid4().hex[:6]}.docx"
    elif not filename.endswith('.docx'):
        filename += '.docx'

    output_path = os.path.join(OUTPUT_DIR, filename)

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(3.0)
        section.right_margin = Cm(2.5)

    # Default paragraph font
    doc.styles['Normal'].font.name = 'Calibri'
    doc.styles['Normal'].font.size = Pt(11)

    _add_header_footer(doc, title, author)
    _add_title_page(doc, title, subtitle, author)

    if include_toc_marker:
        toc_para = doc.add_paragraph()
        toc_run = toc_para.add_run("TABLE OF CONTENTS")
        toc_run.font.bold = True
        toc_run.font.size = Pt(14)
        toc_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)
        toc_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()
        # List section headings as TOC
        for i, section_def in enumerate(sections, 1):
            heading = section_def.get('heading', f'Section {i}')
            level = section_def.get('level', 1)
            indent = "    " * (level - 1)
            toc_line = doc.add_paragraph()
            toc_run = toc_line.add_run(f"{indent}{heading}")
            toc_run.font.size = Pt(11)
            if level == 1:
                toc_run.font.bold = True
        doc.add_page_break()

    # Render sections
    for section_def in sections:
        heading = section_def.get('heading')
        level = section_def.get('level', 1)
        content = section_def.get('content')
        bullets = section_def.get('bullets')
        numbered = section_def.get('numbered_list')
        table_def = section_def.get('table')
        code = section_def.get('code')
        code_lang = section_def.get('code_lang', '')
        image_path = section_def.get('image_path')
        image_caption = section_def.get('image_caption', '')

        if heading:
            _add_section_heading(doc, heading, level)

        if content:
            # Support multiple paragraphs via \n\n
            for para_text in content.split('\n\n'):
                if para_text.strip():
                    _add_paragraph(doc, para_text.strip())

        if bullets:
            _add_bullet_list(doc, bullets, numbered=False)

        if numbered:
            _add_bullet_list(doc, numbered, numbered=True)

        if table_def and 'headers' in table_def and 'rows' in table_def:
            _add_table(doc, table_def['headers'], table_def['rows'])

        if code:
            _add_code_block(doc, code, code_lang)

        if image_path:
            _embed_image(doc, image_path, image_caption)

        doc.add_paragraph()

    doc.save(output_path)

    return {
        "status": "success",
        "path": output_path,
        "filename": filename,
        "file_url": "file:///" + output_path.replace("\\", "/"),
        "sections": len(sections),
        "message": f"Word document created: {filename}"
    }
